name: Node CI

on: [push, deployment_status]

jobs:
  deploy:
    if: (github.event.commits && github.event.ref == 'refs/heads/main') || (github.event.workflow.name == 'Node CI' && github.event.deployment_status.state == 'success')
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [17.x]
    steps:
    - uses: actions/checkout@v3
    - name: Node  v${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
    - run: npm ci
    - run: npm run build --if-present
    - run: npm start
      env:
        DISCORD_TOKEN: ${{ secrets.DISCORD_TOKEN }}
