name: Node CI

on: 
  deployment_status

jobs:
  deploy:
    if: (github.workflow_run.name == 'Node CI' && github.workflow_run.status == 'completed')
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [17.x]
    steps:
    - uses: actions/checkout@v3
    - name: Node  v${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
    - run: npm ci
    - run: npm run build --if-present
    - run: npm start
      env:
        DISCORD_TOKEN: ${{ secrets.DISCORD_TOKEN }}
